name: "build-test"
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "14"

      - run: yarn
      - run: yarn build

      - uses: ethersphere/swarm-actions/upload-dir@v0
        id: upload
        with:
          dir: ./build
          index-document: index.html
          postage-batch-id: ${{ secrets.POSTAGE_BATCH_ID }}
          bee-url: ${{ secrets.BEE_URL }}
          headers: |
            authorization: ${{ secrets.API_TOKEN }}

      - uses: ethersphere/swarm-actions/write-feed@v0
        id: feed
        with:
          reference: ${{ steps.upload.outputs.reference }}
          topic: "swapchat2"
          postage-batch-id: ${{ secrets.POSTAGE_BATCH_ID }}
          bee-url: ${{ secrets.BEE_URL }}
          signer: ${{ secrets.SIGNER }}
          headers: |
            authorization: ${{ secrets.API_TOKEN }}

      - uses: ethersphere/swarm-actions/reference-to-cid@v0
        id: cid
        with:
          reference: ${{ steps.feed.outputs.manifest }}

      - run: |
          echo 'Chunk Reference: ${{ steps.upload.outputs.reference }}'
          echo 'Feed Reference: ${{ steps.feed.outputs.reference }}'
          echo 'Feed Manifest: ${{ steps.feed.outputs.manifest }}'
          echo 'Feed Bzz.link: https://${{ steps.cid.outputs.cid }}.bzz.link'
